### PR TITLE
Verify `blade.compiler` is available before registering the component namespace

### LINKED ISSUE #57078: Target class [blade.compiler] does not exist
### Laravel Version

12.29.0

### PHP Version

8.4.1

### Database Driver & Version

_No response_

### Description

After updating from 12.28.1 to 12.29.0 the `php artisan package:discover` command throws the following exception.

```
local.ERROR: Target class [blade.compiler] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [blade.compiler] does not exist. at /redacted/vendor/laravel/framework/src/Illuminate/Container/Container.php:1163)
```

This is in a console-only project where I didn't have ViewServiceProvider included. Adding that provider does resolve package discovery, but seems like that likely isn't intended? Thanks.

### Steps To Reproduce

Run `php artisan package:discover` on a new project without the ViewServiceProvider loaded.

### PR DESCRIPTION
**Pull request by rodrigopedra**
Closes https://github.com/laravel/framework/issues/57078

Laravel 12.29.0 added a dependency on `phiki/phiki`, which has a discoverable service provider to auto-register a Blade's component namespace.

In apps that opt out of loading Laravel's `ViewServiceProvider`, the `blade.compiler` binding proxied by the `Blade` façade is not available, which causes an error.

Console-only applications can opt out of some providers to reduce size when deployed as PHAR archives.

**This PR**

- Adds a guard around the Blade's component namespace registration to ensure the `blade.compiler` is bound to the container.

### CODE REVIEW

File: src/Adapters/Laravel/PhikiServiceProvider.php [hunk 1]
```diff
@@ -22,6 +22,8 @@ public function register(): void
      */
     public function boot(): void
     {
-        Blade::componentNamespace('Phiki\\Adapters\\Laravel\\Components', 'phiki');
+        if ($this->app->bound('blade.compiler')) {
+            Blade::componentNamespace('Phiki\\Adapters\\Laravel\\Components', 'phiki');
+        }
```
Comment (crynobone) [inline src/Adapters/Laravel/PhikiServiceProvider.php]: Another alternative is to use `Facade::resolved()` helper.

```suggestion
        Blade::resolved(function ($blade) {
            $blade->componentNamespace('Phiki\\Adapters\\Laravel\\Components', 'phiki');
        });
```

Comment (rodrigopedra) [reply src/Adapters/Laravel/PhikiServiceProvider.php]: Thanks @crynobone

**Comment by ryangjchandler** [comment]
Thank you, will get this merged & tagged.
